baseURL = 'https://aask.ltd'
languageCode = 'en-us'
theme = 'hugo-profile'
author = "Aask"
canonifyurls = true
paginate = 10
publishDir = 'docs'


[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer] 
unsafe = true 

[indexes]
  tag = "tags"
  topic = "topics"

title = "Aask's Homepage"

[params]
  favicon= "/images/fav.png"
  
  [params.terms]
    copyright = "Aask. All rights reserved."
  [params.footer]
    [params.footer.recentPosts]
      path = "posts"
      count = 3
      title = "Recent Posts"
      enable = false
      disableFeaturedImage= false
  [params.hero]
    enable = true
    intro = "Hi, my name is"
    subtitle = "Aask Questions!"
    content = "This is a place for me to keep track of my projects and make it a lot easier to share how and why I build the things I do. Check out some of my posts, share if you want, and let me know if you have any questions! </br></br></br> [PS if you're looking for the FTC Writeup click here](https://aask.ltd/ftc_fancy_lights) "
    image = "/images/me_working.png"
    [params.hero.bottomImage]
      enable= false
  [params.navbar]
    brandLogo = "/images/icon.png"
    disableSearch= true

  [params.contact.formspree]
    enable = true
    formId = "https://fabform.io/f/r0fR7zX"
    emailCaption = "Enter your email address"
    messageCaption = "Enter your message here"

  # Shown in the home page
  brand = "AaskLabs"
  googleAnalytics = "G-1YST1BFXGC"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  [params.author]
    name = "Aask Questions"
  
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 2
    url = "/contact/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "posts"
    url = "/posts/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter="aask42"
  # gnusocial="*"
  # facebook="*"
  # weibo="*"
  # tumblr="*"
  # instagram="*"
  # flickr="*"
  # photo500px="*"
  # pinterest="*"
  # youtube="*"
  # vimeo="*"
  # vine="*"
  # slideshare="*"
  linkedin="wietting"
  # xing="*"
  # reddit="*"
  # hackernews="*"
  github="aask42"
  # gitlab="*"
  bitbucket="aaskf"
  # stackoverflow="*"
  # serverfault="*"
  # steam="*"
  # mobygames="*"
  # lastfm="*"
  # discogs="*"
  # keybase="*"
